
name: 'Terraform CI'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: 'auth'
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Set GOOGLE_CREDENTIALS environment variable
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/google-credentials.json
      shell: bash

    - name: Terraform Init
      env:
        GOOGLE_CREDENTIALS: /tmp/google-credentials.json
      run: terraform init

    - name: Terraform Apply
      env:
        GOOGLE_CREDENTIALS: /tmp/google-credentials.json
      run: terraform apply -auto-approve
