name: 'Terraform CI'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Set GOOGLE_CREDENTIALS environment variable
      run: echo "${{ secrets.GCP_SA_KEY }}" > /tmp/google-credentials.json
      shell: bash

    - name: Terraform Init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      run: terraform init

    - name: Terraform Apply
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      run: terraform apply -auto-approve

